#######################################################################
# Split hint components into lists using LLMs
#######################################################################

import os
import json
import argparse
import asyncio
from typing import List, Dict, Any
from tqdm.asyncio import tqdm as async_tqdm

from pychomsky.chchat import AzureOpenAIChatWrapper
from langchain.schema import HumanMessage, SystemMessage


SYSTEM_PROMPT = """**[ROLE & GOAL]**
You are a data wrangler. Your task is to convert numbered list strings into JSON arrays.

**[INSTRUCTIONS]**
- Remove any leading numbering or bullets from each item (e.g., "1.", "2)", "-", "*").
- Preserve the original order.
- Trim whitespace.
- If an item spans multiple lines, join the lines with a single space.
- Do not invent or remove content.

**[OUTPUT FORMAT]**
Return only valid JSON with exactly these keys:
{
  "PLANNING_SKELETON_LIST": ["..."],
  "KNOWLEDGE_COMPONENTS_LIST": ["..."],
  "SOLUTION_BREAKDOWN_LIST": ["..."]
}
"""

USER_PROMPT_TEMPLATE = """**[TASK]**
Split each component into a list without numbering.

PLANNING_SKELETON:
{planning}

KNOWLEDGE_COMPONENTS:
{knowledge}

SOLUTION_BREAKDOWN:
{solution}
"""


def parse_args():
    parser = argparse.ArgumentParser(description="Split hint components into lists")

    parser.add_argument(
        "--input-path",
        type=str,
        default=os.path.join("gen_hints", "hints.jsonl"),
        help="Path to the input JSONL file generated by hint_generation_parallel_scaf.py",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="gen_hints_split",
        help="Directory to save output files",
    )
    parser.add_argument(
        "--output-name",
        type=str,
        default="hints_split.jsonl",
        help="Output JSONL filename",
    )

    parser.add_argument(
        "--model-name",
        type=str,
        default="azure-chat-completions-gpt-5-nano-2025-08-07-sandbox",
        help="Name of the model to use",
    )
    parser.add_argument(
        "--reasoning-effort", type=str, default="low", help="Reasoning effort level"
    )
    parser.add_argument(
        "--max-new-tokens",
        type=int,
        default=4000,
        help="Maximum number of new tokens to generate",
    )

    parser.add_argument(
        "--max-concurrent",
        type=int,
        default=3,
        help="Maximum number of concurrent API calls",
    )
    parser.add_argument(
        "--max-retries",
        type=int,
        default=3,
        help="Maximum number of retries for failed requests",
    )
    parser.add_argument(
        "--retry-delay",
        type=float,
        default=10.0,
        help="Delay in seconds between retries",
    )
    parser.add_argument(
        "--checkpoint-interval",
        type=int,
        default=10,
        help="Save checkpoint every N samples (0 to disable)",
    )

    return parser.parse_args()


def coerce_to_text(value: Any) -> str:
    if isinstance(value, list):
        return "\n".join(str(item) for item in value)
    return str(value)


def make_split_prompt(planning: str, knowledge: str, solution: str) -> List:
    if not planning or not str(planning).strip():
        raise ValueError("PLANNING_SKELETON cannot be empty")
    if not knowledge or not str(knowledge).strip():
        raise ValueError("KNOWLEDGE_COMPONENTS cannot be empty")
    if not solution or not str(solution).strip():
        raise ValueError("SOLUTION_BREAKDOWN cannot be empty")

    user_prompt = USER_PROMPT_TEMPLATE.format(
        planning=coerce_to_text(planning),
        knowledge=coerce_to_text(knowledge),
        solution=coerce_to_text(solution),
    )
    conv = [
        SystemMessage(content=SYSTEM_PROMPT),
        HumanMessage(
            content=[
                {
                    "type": "text",
                    "text": user_prompt,
                }
            ]
        ),
    ]
    return conv


def parse_hint_json(sample: Dict[str, Any]) -> Dict[str, Any]:
    hint_raw = sample.get("hint", "")
    if not hint_raw:
        raise ValueError("Missing hint field")
    if isinstance(hint_raw, dict):
        return hint_raw
    try:
        return json.loads(hint_raw)
    except json.JSONDecodeError as e:
        raise ValueError(f"Failed to parse hint JSON: {str(e)}")


async def split_hint_async(
    llm: AzureOpenAIChatWrapper,
    message: List,
    max_retries: int = 3,
    retry_delay: float = 2.0,
) -> Dict[str, Any]:
    for attempt in range(max_retries):
        try:
            response = await asyncio.to_thread(llm, message)
            output = response.content

            if not output or not output.strip():
                raise ValueError("Empty response from LLM")

            try:
                data = json.loads(output)
            except json.JSONDecodeError as e:
                raise ValueError(f"Failed to parse JSON: {str(e)}")

            required_keys = [
                "PLANNING_SKELETON_LIST",
                "KNOWLEDGE_COMPONENTS_LIST",
                "SOLUTION_BREAKDOWN_LIST",
            ]
            missing = [key for key in required_keys if key not in data]
            if missing:
                raise ValueError(f"Missing keys: {', '.join(missing)}")

            for key in required_keys:
                if not isinstance(data[key], list) or not data[key]:
                    raise ValueError(f"Invalid list for {key}")

            return {"success": True, "split": data, "error": None}

        except Exception as e:
            error_msg = f"Attempt {attempt + 1}/{max_retries} failed: {str(e)}"
            if attempt < max_retries - 1:
                print(f"{error_msg}. Retrying in {retry_delay}s...")
                await asyncio.sleep(retry_delay * (attempt + 1))
            else:
                print(f"{error_msg}. Max retries reached.")
                return {"success": False, "split": {}, "error": str(e)}


async def process_sample(
    llm: AzureOpenAIChatWrapper,
    sample: Dict[str, Any],
    max_retries: int,
    retry_delay: float,
    semaphore: asyncio.Semaphore,
) -> Dict[str, Any]:
    async with semaphore:
        try:
            hint_data = parse_hint_json(sample)
            message = make_split_prompt(
                hint_data.get("PLANNING_SKELETON", ""),
                hint_data.get("KNOWLEDGE_COMPONENTS", ""),
                hint_data.get("SOLUTION_BREAKDOWN", ""),
            )
        except Exception as e:
            return {
                **sample,
                "split_success": False,
                "split_error": str(e),
            }

        result = await split_hint_async(
            llm, message, max_retries=max_retries, retry_delay=retry_delay
        )

        return {
            **sample,
            "planning_skeleton_list": result["split"].get(
                "PLANNING_SKELETON_LIST", []
            ),
            "knowledge_components_list": result["split"].get(
                "KNOWLEDGE_COMPONENTS_LIST", []
            ),
            "solution_breakdown_list": result["split"].get(
                "SOLUTION_BREAKDOWN_LIST", []
            ),
            "split_success": result["success"],
            "split_error": result["error"],
        }


def read_jsonl(input_path: str) -> List[Dict[str, Any]]:
    if not os.path.exists(input_path):
        raise FileNotFoundError(f"Input file not found: {input_path}")

    samples = []
    with open(input_path, "r", encoding="utf8") as f:
        for line_num, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                samples.append(json.loads(line))
            except json.JSONDecodeError as e:
                raise ValueError(f"Invalid JSON on line {line_num}: {str(e)}")

    if not samples:
        raise ValueError("Input file is empty")
    return samples


def save_results(samples: List[Dict[str, Any]], output_path: str):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf8") as f:
        for sample in samples:
            json.dump(sample, f, ensure_ascii=False)
            f.write("\n")


async def main_async(args):
    print(f"Loading input from {args.input_path}...")
    samples = read_jsonl(args.input_path)
    print(f"Loaded {len(samples)} samples")

    print(f"Initializing LLM: {args.model_name}")
    llm = AzureOpenAIChatWrapper(
        model_name=args.model_name,
        max_completion_tokens=args.max_new_tokens,
        reasoning_effort=args.reasoning_effort,
        response_format={"type": "json_object"},
    )

    semaphore = asyncio.Semaphore(args.max_concurrent)

    tasks = [
        process_sample(llm, sample, args.max_retries, args.retry_delay, semaphore)
        for sample in samples
    ]

    results = []
    for idx, coro in enumerate(
        async_tqdm(
            asyncio.as_completed(tasks), total=len(tasks), desc="Splitting hints"
        )
    ):
        result = await coro
        results.append(result)

        if args.checkpoint_interval > 0 and (idx + 1) % args.checkpoint_interval == 0:
            checkpoint_path = os.path.join(
                args.output_dir, f"hints_split_checkpoint_{idx + 1}.jsonl"
            )
            save_results(results, checkpoint_path)
            print(f"Checkpoint saved: {checkpoint_path}")

    if any("id" in sample for sample in results):
        results.sort(key=lambda x: x.get("id"))

    output_path = os.path.join(args.output_dir, args.output_name)
    save_results(results, output_path)

    successful = sum(1 for r in results if r.get("split_success", False))
    failed = len(results) - successful

    print(f"\n{'=' * 50}")
    print("Splitting complete!")
    print(f"Total samples: {len(results)}")
    print(f"Successful: {successful}")
    print(f"Failed: {failed}")
    print(f"Success rate: {successful / len(results) * 100:.1f}%")
    print(f"Output saved to: {output_path}")
    print(f"{'=' * 50}")


def main(args):
    try:
        asyncio.run(main_async(args))
    except KeyboardInterrupt:
        print("\nInterrupted by user")
    except Exception as e:
        print(f"\nError: {str(e)}")
        raise


if __name__ == "__main__":
    args = parse_args()
    main(args)
