# the hint config will override default ppo_trainer.yaml

hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

trainer:
  # Threshold for switching hint levels based on per-prompt rollout accuracy.
  hint_accuracy_min_threshold: 0.0
  hint_accuracy_max_threshold: 0.25
